### PR TITLE
Bump version 020

### PR DESCRIPTION
**Pull request by agardelakos**

### CODE REVIEW

**Review by fgypas — APPROVED** [review]
LGTM

**Comment by fgypas** [comment]
I think we need to discuss the docker rate limit (https://www.docker.com/increase-rate-limit). This is why the CI fails here...

**Comment by vsoch** [comment]
If you are re-using layers you can save your cache, [example in Travis](https://testdriven.io/blog/faster-ci-builds-with-docker-cache/) so you don't need to re-pull the Python base.

**Comment by fgypas** [comment]
@agardelakos I manually restarted the CI. You can finish the PR now.
I will open an issue for the layers to follow @vsoch 's recommendation.

**Pull request merged**
