### PR TITLE
feature/10 Clean up DB button

### PR DESCRIPTION
**Pull request by dafentoulis**
Added clean up DB button on top left
Removed colors from buttons to avoid confusion with status
Minor beautification changes

### CODE REVIEW

**Review by fgypas — CHANGES_REQUESTED** [review]
@dafentoulis Can you please pull also the changes from develop? I think that develop is ahead of the current branch by one commit.

**Comment by gkostoulas** [comment]
> @dafentoulis Can you please pull also the changes from develop? I think that develop is ahead of the current branch by one commit.

If there is no conflict and the commit is irrelevant there is no problem to merge without rebasing to develop.

**Comment by dafentoulis** [comment]
Indeed, there is no problem with merging this.

**Comment by fgypas** [comment]
Oh, ok. LGTM then.

**Review by fgypas — APPROVED** [review]

**Pull request merged**
