### PR TITLE
feature/95 table refactor,added pagination, sorting and actions

### PR DESCRIPTION
**Pull request by dafentoulis**
issues/95:
-Added pagination
-Added sorting
-Added Actions columns with edit and delete button
-Added modal for delete confirmation
-Added modals for delete and edit database errors
-Partial css/js cleanup

Global search button now only triggers the searchResults page as tables contain a dedicated search button.
Deleting a workflow from workflow/id page, will redirect to /workflows
After database error, page will reload.

### CODE REVIEW

**Review by fgypas — COMMENTED** [review]
I don't see any changes in terms of functionality. The only difference that I observed is the color of the buttons. I installed the new version with `pip install .` (as usual). Should I install it somehow differently?

**Comment by dafentoulis** [comment]
> I don't see any changes in terms of functionality. The only difference that I observed is the color of the buttons. I installed the new version with `pip install .` (as usual). Should I install it somehow differently (e.g. for javascript)?

Which buttons are you referring too? Add and edit buttons were not there before.
Perhaps you need to hard reload. If you already had your browser open, then you need to clear your cache so that new JS can be loaded.

**Comment by fgypas** [comment]
> > I don't see any changes in terms of functionality. The only difference that I observed is the color of the buttons. I installed the new version with `pip install .` (as usual). Should I install it somehow differently (e.g. for javascript)?
> 
> Which buttons are you referring too? Add and edit buttons were not there before.
> Perhaps you need to hard reload. If you already had your browser open, then you need to clear your cache so that new JS can be loaded. Mitsatsos got my changes and it worked fine. Unless I have to do something related to the pip installer

Thanks. Indeed it was an issue with the cache. I think it's working fine now and it really looks nice.

**Review by fgypas — APPROVED** [review]
LGTM!

**Comment by dafentoulis** [comment]
> > > I don't see any changes in terms of functionality. The only difference that I observed is the color of the buttons. I installed the new version with `pip install .` (as usual). Should I install it somehow differently (e.g. for javascript)?
> > 
> > 
> > Which buttons are you referring too? Add and edit buttons were not there before.
> > Perhaps you need to hard reload. If you already had your browser open, then you need to clear your cache so that new JS can be loaded. Mitsatsos got my changes and it worked fine. Unless I have to do something related to the pip installer
> 
> Thanks. Indeed it was an issue with the cache. I think it's working fine now and it really looks nice.

Thank you, let me know if you see any weird bugs there.

**Pull request merged**
